### YamlMime:ManagedReference
items:
- uid: GTA.PedConfigFlags
  commentId: T:GTA.PedConfigFlags
  id: PedConfigFlags
  parent: GTA
  children:
  - GTA.PedConfigFlags.GetConfigFlag(GTA.PedConfigFlagToggles)
  - GTA.PedConfigFlags.KnockOffVehicleType
  - GTA.PedConfigFlags.PassengerIndexToUseInAGroup
  - GTA.PedConfigFlags.PedLegIKMode
  - GTA.PedConfigFlags.SetConfigFlag(GTA.PedConfigFlagToggles,System.Boolean)
  langs:
  - csharp
  - vb
  name: PedConfigFlags
  nameWithType: PedConfigFlags
  fullName: GTA.PedConfigFlags
  type: Class
  assemblies:
  - ScriptHookVDotNet3
  namespace: GTA
  syntax:
    content: public sealed class PedConfigFlags
    content.vb: Public NotInheritable Class PedConfigFlags
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
- uid: GTA.PedConfigFlags.GetConfigFlag(GTA.PedConfigFlagToggles)
  commentId: M:GTA.PedConfigFlags.GetConfigFlag(GTA.PedConfigFlagToggles)
  id: GetConfigFlag(GTA.PedConfigFlagToggles)
  parent: GTA.PedConfigFlags
  langs:
  - csharp
  - vb
  name: GetConfigFlag(PedConfigFlagToggles)
  nameWithType: PedConfigFlags.GetConfigFlag(PedConfigFlagToggles)
  fullName: GTA.PedConfigFlags.GetConfigFlag(GTA.PedConfigFlagToggles)
  type: Method
  assemblies:
  - ScriptHookVDotNet3
  namespace: GTA
  syntax:
    content: public bool GetConfigFlag(PedConfigFlagToggles configFlagToggle)
    parameters:
    - id: configFlagToggle
      type: GTA.PedConfigFlagToggles
    return:
      type: System.Boolean
    content.vb: Public Function GetConfigFlag(configFlagToggle As PedConfigFlagToggles) As Boolean
  overload: GTA.PedConfigFlags.GetConfigFlag*
- uid: GTA.PedConfigFlags.SetConfigFlag(GTA.PedConfigFlagToggles,System.Boolean)
  commentId: M:GTA.PedConfigFlags.SetConfigFlag(GTA.PedConfigFlagToggles,System.Boolean)
  id: SetConfigFlag(GTA.PedConfigFlagToggles,System.Boolean)
  parent: GTA.PedConfigFlags
  langs:
  - csharp
  - vb
  name: SetConfigFlag(PedConfigFlagToggles, bool)
  nameWithType: PedConfigFlags.SetConfigFlag(PedConfigFlagToggles, bool)
  fullName: GTA.PedConfigFlags.SetConfigFlag(GTA.PedConfigFlagToggles, bool)
  type: Method
  assemblies:
  - ScriptHookVDotNet3
  namespace: GTA
  syntax:
    content: public void SetConfigFlag(PedConfigFlagToggles configFlagToggle, bool value)
    parameters:
    - id: configFlagToggle
      type: GTA.PedConfigFlagToggles
    - id: value
      type: System.Boolean
    content.vb: Public Sub SetConfigFlag(configFlagToggle As PedConfigFlagToggles, value As Boolean)
  overload: GTA.PedConfigFlags.SetConfigFlag*
  nameWithType.vb: PedConfigFlags.SetConfigFlag(PedConfigFlagToggles, Boolean)
  fullName.vb: GTA.PedConfigFlags.SetConfigFlag(GTA.PedConfigFlagToggles, Boolean)
  name.vb: SetConfigFlag(PedConfigFlagToggles, Boolean)
- uid: GTA.PedConfigFlags.KnockOffVehicleType
  commentId: P:GTA.PedConfigFlags.KnockOffVehicleType
  id: KnockOffVehicleType
  parent: GTA.PedConfigFlags
  langs:
  - csharp
  - vb
  name: KnockOffVehicleType
  nameWithType: PedConfigFlags.KnockOffVehicleType
  fullName: GTA.PedConfigFlags.KnockOffVehicleType
  type: Property
  assemblies:
  - ScriptHookVDotNet3
  namespace: GTA
  syntax:
    content: public KnockOffVehicleType KnockOffVehicleType { get; set; }
    parameters: []
    return:
      type: GTA.KnockOffVehicleType
    content.vb: Public Property KnockOffVehicleType As KnockOffVehicleType
  overload: GTA.PedConfigFlags.KnockOffVehicleType*
- uid: GTA.PedConfigFlags.PedLegIKMode
  commentId: P:GTA.PedConfigFlags.PedLegIKMode
  id: PedLegIKMode
  parent: GTA.PedConfigFlags
  langs:
  - csharp
  - vb
  name: PedLegIKMode
  nameWithType: PedConfigFlags.PedLegIKMode
  fullName: GTA.PedConfigFlags.PedLegIKMode
  type: Property
  assemblies:
  - ScriptHookVDotNet3
  namespace: GTA
  syntax:
    content: public PedLegIKMode PedLegIKMode { get; set; }
    parameters: []
    return:
      type: GTA.PedLegIKMode
    content.vb: Public Property PedLegIKMode As PedLegIKMode
  overload: GTA.PedConfigFlags.PedLegIKMode*
- uid: GTA.PedConfigFlags.PassengerIndexToUseInAGroup
  commentId: P:GTA.PedConfigFlags.PassengerIndexToUseInAGroup
  id: PassengerIndexToUseInAGroup
  parent: GTA.PedConfigFlags
  langs:
  - csharp
  - vb
  name: PassengerIndexToUseInAGroup
  nameWithType: PedConfigFlags.PassengerIndexToUseInAGroup
  fullName: GTA.PedConfigFlags.PassengerIndexToUseInAGroup
  type: Property
  assemblies:
  - ScriptHookVDotNet3
  namespace: GTA
  syntax:
    content: public VehicleSeat PassengerIndexToUseInAGroup { get; set; }
    parameters: []
    return:
      type: GTA.VehicleSeat
    content.vb: Public Property PassengerIndexToUseInAGroup As VehicleSeat
  overload: GTA.PedConfigFlags.PassengerIndexToUseInAGroup*
references:
- uid: GTA
  commentId: N:GTA
  isExternal: true
  href: GTA.html
  name: GTA
  nameWithType: GTA
  fullName: GTA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: GTA.PedConfigFlags.GetConfigFlag*
  commentId: Overload:GTA.PedConfigFlags.GetConfigFlag
  isExternal: true
  href: GTA.PedConfigFlags.html#GTA_PedConfigFlags_GetConfigFlag_GTA_PedConfigFlagToggles_
  name: GetConfigFlag
  nameWithType: PedConfigFlags.GetConfigFlag
  fullName: GTA.PedConfigFlags.GetConfigFlag
- uid: GTA.PedConfigFlagToggles
  commentId: T:GTA.PedConfigFlagToggles
  parent: GTA
  isExternal: true
  href: GTA.PedConfigFlagToggles.html
  name: PedConfigFlagToggles
  nameWithType: PedConfigFlagToggles
  fullName: GTA.PedConfigFlagToggles
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: GTA.PedConfigFlags.SetConfigFlag*
  commentId: Overload:GTA.PedConfigFlags.SetConfigFlag
  isExternal: true
  href: GTA.PedConfigFlags.html#GTA_PedConfigFlags_SetConfigFlag_GTA_PedConfigFlagToggles_System_Boolean_
  name: SetConfigFlag
  nameWithType: PedConfigFlags.SetConfigFlag
  fullName: GTA.PedConfigFlags.SetConfigFlag
- uid: GTA.PedConfigFlags.KnockOffVehicleType*
  commentId: Overload:GTA.PedConfigFlags.KnockOffVehicleType
  isExternal: true
  href: GTA.PedConfigFlags.html#GTA_PedConfigFlags_KnockOffVehicleType
  name: KnockOffVehicleType
  nameWithType: PedConfigFlags.KnockOffVehicleType
  fullName: GTA.PedConfigFlags.KnockOffVehicleType
- uid: GTA.KnockOffVehicleType
  commentId: T:GTA.KnockOffVehicleType
  parent: GTA
  isExternal: true
  href: GTA.KnockOffVehicleType.html
  name: KnockOffVehicleType
  nameWithType: KnockOffVehicleType
  fullName: GTA.KnockOffVehicleType
- uid: GTA.PedConfigFlags.PedLegIKMode*
  commentId: Overload:GTA.PedConfigFlags.PedLegIKMode
  isExternal: true
  href: GTA.PedConfigFlags.html#GTA_PedConfigFlags_PedLegIKMode
  name: PedLegIKMode
  nameWithType: PedConfigFlags.PedLegIKMode
  fullName: GTA.PedConfigFlags.PedLegIKMode
- uid: GTA.PedLegIKMode
  commentId: T:GTA.PedLegIKMode
  parent: GTA
  isExternal: true
  href: GTA.PedLegIKMode.html
  name: PedLegIKMode
  nameWithType: PedLegIKMode
  fullName: GTA.PedLegIKMode
- uid: GTA.PedConfigFlags.PassengerIndexToUseInAGroup*
  commentId: Overload:GTA.PedConfigFlags.PassengerIndexToUseInAGroup
  isExternal: true
  href: GTA.PedConfigFlags.html#GTA_PedConfigFlags_PassengerIndexToUseInAGroup
  name: PassengerIndexToUseInAGroup
  nameWithType: PedConfigFlags.PassengerIndexToUseInAGroup
  fullName: GTA.PedConfigFlags.PassengerIndexToUseInAGroup
- uid: GTA.VehicleSeat
  commentId: T:GTA.VehicleSeat
  parent: GTA
  isExternal: true
  href: GTA.VehicleSeat.html
  name: VehicleSeat
  nameWithType: VehicleSeat
  fullName: GTA.VehicleSeat
